### ISSUE TITLE
Failure to install the plugin

### ISSUE THREAD

**Issue by alexkushnir** [sprotheroe/vagrant-disksize#26]
Unable to install the disksize plugin. 
My setup is:
Windows 7 64-bit, Vagrant 2.1.5

Below is the console output: 

`λ vagrant plugin install disksize
Installing the 'disksize' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:784:in \`[]=\': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:784:in \`sender'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:525:in \`block in fetch_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1133:in \`block (3 levels) in resolv'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1131:in \`each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1131:in \`block (2 levels) in resolv'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1130:in \`each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1130:in \`block in resolv'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1128:in \`each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1128:in \`resolv'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:520:in \`fetch_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:510:in \`each_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:491:in \`getresource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in \`api_endpoint'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:47:in \`api_uri'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:183:in \`load_specs'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:424:in \`block in validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in \`each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in \`each_source'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:422:in \`validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:330:in \`internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:128:in \`install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/manager.rb:138:in \`block in install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/manager.rb:148:in \`install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/action/install_gem.rb:30:in \`call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in \`call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in \`call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in \`block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in \`busy'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in \`run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/base.rb:14:in \`action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/install.rb:70:in \`block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/install.rb:69:in \`each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/install.rb:69:in `\execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/root.rb:66:in \`execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/cli.rb:54:in \`execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:291:in \`cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/bin/vagrant:164:in \`<main>'`

Your help is appreciated

**Comment by FlorianTolk** [comment]
having a similar issue:
```
$ vagrant plugin install vagrant-disksize
Installing the 'vagrant-disksize' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:949:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	from /usr/bin/vagrant:173:in `<main>'
```
