### ISSUE TITLE
Can't install vagrant-disksize on fedora 30 with Vagrant 2.2.4 and rubygem-rdoc-6.1.0

### ISSUE THREAD

**Issue by Guigzai** [sprotheroe/vagrant-disksize#32]
Hi,

I use fedora 30 :
 * Vagrant 2.2.4
 * rubygem-rdoc-6.1.0-120.fc30.noarch

When I try to install plugin, an error occur :
vagrant plugin install vagrant-disksize
Installing the 'vagrant-disksize' plugin. This can take a few minutes...
/usr/share/gems/gems/psych-3.1.0/lib/psych.rb:237: warning: already initialized constant Psych::LIBYAML_VERSION
/usr/share/ruby/psych.rb:237: warning: previous definition of LIBYAML_VERSION was here
/usr/share/gems/gems/psych-3.1.0/lib/psych.rb:239: warning: already initialized constant Psych::NOT_GIVEN
/usr/share/ruby/psych.rb:239: warning: previous definition of NOT_GIVEN was here
Fetching micromachine-3.0.0.gem
Fetching vagrant-vbguest-0.19.0.gem
Parsing documentation for dotenv-deployment-0.0.2
Parsing documentation for dotenv-0.11.1
Parsing documentation for vagrant-env-0.0.3
Parsing documentation for vagrant-newdisk-0.0.3
Parsing documentation for vagrant-persistent-storage-0.0.47
Parsing documentation for vagrant-proxyconf-2.0.1
Parsing documentation for vagrant-reload-0.0.1
Parsing documentation for micromachine-3.0.0
Installing ri documentation for micromachine-3.0.0
Parsing documentation for vagrant-vbguest-0.19.0
Installing ri documentation for vagrant-vbguest-0.19.0
Parsing documentation for vagrant-disksize-0.1.3
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/bin/ruby -c lib/vagrant/disksize.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

        (NoMethodError) undefined method `[]' for nil:NilClass

Traceback (most recent call last):
        42: from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
        41: from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
        40: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/bin/vagrant:182:in `<top (required)>'
        39: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/environment.rb:292:in `cli'
        38: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/cli.rb:66:in `execute'
        37: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/plugins/commands/plugin/command/root.rb:66:in `execute'
        36: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/plugins/commands/plugin/command/install.rb:69:in `execute'
        35: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/plugins/commands/plugin/command/install.rb:69:in `each'
        34: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        33: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/plugins/commands/plugin/command/base.rb:14:in `action'
        32: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
        31: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
        30: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
        29: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
        28: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        27: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        26: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        25: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        24: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
        23: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        22: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/bundler.rb:133:in `install'
        21: from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/bundler.rb:372:in `internal_install'
        20: from /usr/share/rubygems/rubygems/request_set.rb:298:in `install_into'
        19: from /usr/share/rubygems/rubygems/request_set.rb:322:in `install_hooks'
        18: from /usr/share/rubygems/rubygems/request_set.rb:322:in `each'
        17: from /usr/share/rubygems/rubygems/request_set.rb:323:in `block in install_hooks'
        16: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rubygems_hook.rb:55:in `generation_hook'
        15: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rubygems_hook.rb:55:in `each'
        14: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
        13: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rubygems_hook.rb:189:in `generate'
        12: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rubygems_hook.rb:189:in `chdir'
        11: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rubygems_hook.rb:190:in `block in generate'
        10: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:414:in `parse_files'
         9: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:414:in `map'
         8: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:416:in `block in parse_files'
         7: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:360:in `parse_file'
         6: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/parser.rb:191:in `for'
         5: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/parser.rb:191:in `new'
         4: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/parser/ruby.rb:180:in `initialize'
         3: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/parser/ripper_state_lex.rb:578:in `parse'
         2: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/parser/ripper_state_lex.rb:346:in `get_squashed_tk'
         1: from /usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/parser/ripper_state_lex.rb:473:in `get_heredoc_tk'
/usr/share/gems/gems/rdoc-6.1.0/lib/rdoc/parser/ripper_state_lex.rb:496:in `heredoc_end?': undefined method `[]' for nil:NilClass (NoMethodError)

Regards

**Comment by tsmilam** [comment]
I was able to workaround this by uninstalling the Fedora vagrant packages running Hashicorp's vagrant binary. It's not a Fedora problem, btw. Seems there were some vagrant plugins built against old dependencies.

**Comment by bgamari** [comment]
I have also run into this.

**Comment by ghost** [comment]
As a temporary workaround, just do `dnf remove rubygem-rdoc` to get it working.
